version: '3.9'


services:
  backend:
    build: .
    ports:
      - "3000:3000"
    networks:
      - backend-network
    depends_on:
      - postgresql

  postgresql:
    image: postgis/postgis
    restart: unless-stopped
    environment:
        POSTGRES_USER: 'user'
        POSTGRES_PASSWORD: 'password'
        POSTGRES_DB: 'api'
    ports:
      - '5432:5432'
    networks:
      - backend-network


networks:
  backend-network: